version: "3.9"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto/config:/mosquitto/config"
    networks:
      - mosquitto_net
    ports:
      - "1883:1883"
      - "9001:9001"
  node-red:
    container_name: nodered
    depends_on:
      - mosquitto
    image: nodered/node-red
    volumes:
      - "./node-red/data:/data"
    networks:
      - mosquitto_net
    ports:
      - "1880:1880"
networks:
  mosquitto_net:
    name: mosquitto_net
